# Generated by Django 3.1.3 on 2020-11-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contact', models.EmailField(max_length=254)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('occupation', models.CharField(choices=[('E', 'Estágio'), ('J', 'Junior'), ('P', 'Pleno'), ('S', 'Sênior')], max_length=1)),
                ('contract', models.CharField(choices=[('PJ', 'PJ'), ('CLT', 'CLT')], max_length=3)),
                ('remote', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('salary', models.CharField(blank=True, choices=[('0-1000', 'R$ 0,00 - R$ 1.000,00'), ('1000-3000', 'R$ 1.000,01 - R$ 3.000,00'), ('3000-6000', 'R$ 3.000,01 - R$ 6.000,00'), ('6000-10000', 'R$ 6.000,01 - R$ 10.000,00'), ('10000+', 'R$ 10.000,00 ou mais')], max_length=10)),
            ],
        ),
    ]
