# Generated by Django 3.1.3 on 2020-11-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appportalvagasaju', '0002_auto_20201127_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
