# Generated by Django 3.1.3 on 2020-12-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportalvagasaju', '0004_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
