# Generated by Django 3.1.3 on 2020-12-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportalvagasaju', '0005_auto_20201202_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
